"""Remove unique constraint from artist name

Revision ID: 468273f580aa
Revises: 0d2baa7510fe
Create Date: 2025-04-18 14:10:37.145340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468273f580aa'
down_revision: Union[str, None] = '0d2baa7510fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artists_name', table_name='artists')
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.create_index('ix_artists_name', 'artists', ['name'], unique=True)
    # ### end Alembic commands ###
