"""Remove unique constraint from song title

Revision ID: 63a158ca1a9c
Revises: 45c80f6f00e4
Create Date: 2025-04-18 01:30:39.608707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a158ca1a9c'
down_revision: Union[str, None] = '45c80f6f00e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_songs_title', table_name='songs')
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.create_index('ix_songs_title', 'songs', ['title'], unique=True)
    # ### end Alembic commands ###
